{% set version = "0.3.1" %}

package:
  name: m2r
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/m2r/m2r-{{ version }}.tar.gz
  sha256: aafb67fc49cfb1d89e46a3443ac747e15f4bb42df20ed04f067ad9efbee256ab

build:
  number: 0
  noarch: python
  entry_points:
    - m2r = m2r:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docutils
    - mistune

test:
  commands:
    - m2r --help

about:
  home: https://github.com/miyakogi/m2r
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Markdown and reStructuredText in a single file

extra:
  recipe-maintainers:
    - ocefpaf
