{% set version = "0.2.1" %}

package:
  name: m2r
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/m2r/m2r-{{ version }}.tar.gz
  sha256: bf90bad66cda1164b17e5ba4a037806d2443f2a4d5ddc9f6a5554a0322aaed99

build:
  number: 0
  noarch: python
  entry_points:
    - m2r = m2r:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docutils
    - mistune

test:
  commands:
    - m2r --help

about:
  home: https://github.com/miyakogi/m2r
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Markdown and reStructuredText in a single file

extra:
  recipe-maintainers:
    - ocefpaf
