travis:
  secure:
    BINSTAR_TOKEN: sa8mpnsy/3Vnq2FMZ4Saj59xAga3fGtyaVSEdh9b/bKDFoRHTRxAxA1+vbRyZgITgShamqNviGsDWF6Xp3a/k6zOfTIJbpGovdR7iL82Wr17AtleJ+2n2ZgPt0iSF/niDOvHK+krIG6mXK+QhEAQhuUNmm6Rfp6TJO1a9USUvBVY2jWo5e63aW1zSrM63v81U80xgTcKT2EekvA3UomA/8cwzMQWWaHWHCJQJN6G8fiHmzNiWrcTMjpqQrE8X+V1LFdZ+VOClbrTfg8yoLz/1ohx6l1GPRpZWk5bKkSCKbJjS9eNI1NKhTDv184glpWkk/VWlSDwqEGPrkK59IlfjKGv0uG/vDR0SKZU81gTsZo4cdJBRh/QeSZeCr71TqdRZZuSIpk+OF5JCj4RHmLdr9wW75c3E1F8vFSRAfLpr1lBcChT75FGGWqQrhIplAIzZ1tKjgAqwN844XG64lKg5YHhZmvTN/sGdtqjPlpGLhD4TrZSQFwO/HKqyufUrw34WVPkZVdR8Dxg9qOtMsuOGHzcWd2pmWWuj/+/lyzFog9QmOeJnyDbLoElMUgk3MAMADQF162xQizHcih5679I28Gp1PTTme39WXALfIMMOGYBbZagEPe1sIPv8J7aVG4abd7c+cp3uResisE91ZhtRKCTrX4PC5nq+DhAFkyx6YU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
